django_web_project/accounts/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import registration, Login, Logout, Profile, ProfileChangeView

app_name = 'accounts_app'

urlpatterns = [
    path('registration', registration, name='registration'),
    path('terms_of_service', TemplateView.as_view(template_name='terms_of_service.html'), name='terms_of_service'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('profile/<int:pk>', Profile.as_view(), name='profile'),
    path('profile_change/<int:pk>', ProfileChangeView.as_view(), name='profile_change'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_web_project/django_web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    #path('blog/', include('blog.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

django_web_project/home/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

app_name = 'home_app'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

django_web_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='images/')
    bio = models.TextField(null=True)

django_web_project/blog/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    published = (
        ('Draft', 'draft'),
        ('Published', 'published'),
    )

    image = models.ImageField(upload_to='blog_images')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=128, blank=False)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    status = models.CharField(max_length=32, choices=published, default='Draft')
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

django_web_project/home/models.py
from django.db import models

# Create your models here.

django_web_project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

from .models import CustomUser


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Username', max_length=32,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    email = forms.EmailField(label='Email', max_length=254,
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label='Password', max_length=32,
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='Password confirm', max_length=32,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Password confirm'}))
    terms_of_service = forms.BooleanField(label='Terms of service', required=True, disabled=False,
                                          widget=forms.CheckboxInput(
                                              attrs={'class': 'form-check-label', 'align': 'left'}
                                          ))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'terms_of_service')

        """widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'})
        }"""


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=64,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(label='Password', max_length=32,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = CustomUser
        fields = ('username', 'password')


class ProfileChangeForm(forms.ModelForm):
    image = forms.ImageField(required=False, widget=forms.FileInput())
    email = forms.EmailField(label='Email', max_length=254,
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    bio = forms.CharField(label='Bio',
                          widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Bio'}))

    class Meta:
        model = CustomUser
        fields = ('image', 'email', 'bio')

django_web_project/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

from .forms import RegistrationForm, LoginForm, ProfileChangeForm
from .models import CustomUser


def registration(request):
    if request.user.is_authenticated:
        return redirect('home_app:home')
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created. You can log in now!')
            return redirect('accounts_app:login')
        else:
            messages.error(request, f'{form.errors}')
            return redirect('accounts_app:registration')
    else:
        form = RegistrationForm()
    context = {'form': form}
    return render(request, 'registration.html', context=context)


class Login(LoginView):
    template_name = 'login.html'
    redirect_field_name = 'home_app:home'
    authentication_form = LoginForm
    redirect_authenticated_user = True


class Logout(LogoutView):
    redirect_field_name = 'home_app:home'


class Profile(DetailView):
    model = CustomUser
    template_name = 'profile.html'


class ProfileChangeView(UpdateView):
    template_name = 'profile_change.html'
    form_class = ProfileChangeForm
    model = CustomUser

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("accounts_app:profile", kwargs={"pk": pk})

# Create your views here.

django_web_project/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from .models import Post


class PostList(ListView):
    model = Post
    template_name = 'posts_list.html'

django_web_project/home/views.py
from django.shortcuts import render

# Create your views here.

django_web_project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home_app:home' %}">Home</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <div class="me-2"><a class="nav-link" href="{% url 'accounts_app:logout' %}">Logout</a></div>
        {% else %}
          <div class="me-2"><a class="nav-link" href="{% url 'accounts_app:registration' %}">Register</a></div>
          <div class="me-2"><a class="nav-link" href="{% url 'accounts_app:login' %}">Login</a></div>
        {% endif %}
      </div>
    </div>
  </nav>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <script src="https://kit.fontawesome.com/9a82266100.js" crossorigin="anonymous"></script>
  </body>
</html>

django_web_project/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-secondary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'assets/img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Home Page</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Machine Learning Engineer</p>
    </div>
</header>


<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
<script src="{% static 'js/scripts.js' %}"></script>

{% endblock %}

django_web_project/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<style>
  btn-color{
    background-color: #0e1c36;
    color: #fff;

  }

  .profile-image-pic{
    height: 200px;
    width: 200px;
    object-fit: cover;
  }



  .cardbody-color{
    background-color: #ebf2fa;
  }

  a{
    text-decoration: none;
  }
</style>
<section class="vh-100 bg-secondary" style="background-color: #eee;">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2 class="text-center text-dark mt-5">Login</h2>
        <div class="card my-5">

          <form class="card-body cardbody-color p-lg-5" method="POST">

            {% csrf_token %}

            <div class="text-center">
              <img src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295397__340.png" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3"
                width="200px" alt="profile">
            </div>

            <div class="mb-3">
              {{ form.username }}
            </div>
            <div class="mb-3">
              {{ form.password }}
            </div>
            <div class="text-center"><button type="submit" class="btn btn-primary px-5 mb-5 w-100">Login</button></div>
            <div id="emailHelp" class="form-text text-center mb-5 text-dark">Not
              Registered? <a href="{% url 'accounts_app:registration' %}" class="text-dark fw-bold"> Create an Account</a>
            </div>
          </form>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock %}

django_web_project/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    Profile
{% endblock %}

{% block content %}
<style>
  * {
      margin: 0;
      padding: 0
  }

  body {
      background-color: #000
  }

  .card {
      width: 350px;
      background-color: #efefef;
      border: none;
      cursor: pointer;
      transition: all 0.5s
  }

  .image img {
      transition: all 0.5s
  }

  .card:hover .image img {
      transform: scale(1.5)
  }

  .btn {
      height: 140px;
      width: 140px;
      border-radius: 50%
  }

  .name {
      font-size: 22px;
      font-weight: bold
  }

  .idd {
      font-size: 14px;
      font-weight: 600
  }

  .idd1 {
      font-size: 12px
  }

  .number {
      font-size: 22px;
      font-weight: bold
  }

  .follow {
      font-size: 12px;
      font-weight: 500;
      color: #444444
  }

  .btn1 {
      height: 40px;
      width: 150px;
      border: none;
      background-color: #000;
      color: #aeaeae;
      font-size: 15px
  }

  .text span {
      font-size: 13px;
      color: #545454;
      font-weight: 500
  }

  .icons i {
      font-size: 19px
  }

  hr .new1 {
      border: 1px solid
  }

  .join {
      font-size: 14px;
      #color: #a0a0a0;
      font-weight: bold
  }

  .date {
      background-color: #ccc
  }
</style>
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class=" image d-flex flex-column justify-content-center align-items-center"> <button class="btn btn-secondary"> <img src="https://i.imgur.com/wvxPV9S.png" height="100" width="100" /></button> <span class="name mt-3">{{ object.username }}</span>
            <div class="d-flex flex-row justify-content-center align-items-center gap-2"> <span class="idd1">{{ object.email }}</span> <span><i class="fa fa-copy"></i></span> </div>
            <div class=" d-flex mt-2">
                <a href="{% url 'accounts_app:profile_change' object.id %}" class="btn1 btn-dark">
                    <div align="center">Edit Profile</div>
                </a>
            </div>
            <div class="text mt-3"> <span>Bio: {{ object.bio }}</span> </div>
            <div class=" px-2 rounded mt-4 date "> <span class="join">Last visit: {{ object.last_login }}</span> </div>
            <div class=" px-2 rounded mt-4 date "> <span class="join">Registred: {{ object.date_joined }}</span> </div>
        </div>
    </div>
</div>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}

django_web_project/templates/profile_change.html
{% extends 'base.html' %}

{% block title %}
    Change Profile
{% endblock %}

{% block content %}
<style>
  * {
      margin: 0;
      padding: 0
  }

  body {
      background-color: #000
  }

  .card {
      width: 350px;
      background-color: #efefef;
      border: none;
      cursor: pointer;
      transition: all 0.5s
  }

  .image img {
      transition: all 0.5s
  }

  .card:hover .image img {
      transform: scale(1.5)
  }

  .name {
      font-size: 22px;
      font-weight: bold
  }

  .idd {
      font-size: 14px;
      font-weight: 600
  }

  .idd1 {
      font-size: 12px
  }

  .number {
      font-size: 22px;
      font-weight: bold
  }

  .follow {
      font-size: 12px;
      font-weight: 500;
      color: #444444
  }

  .btn1 {
      height: 40px;
      width: 150px;
      border: none;
      background-color: #000;
      color: #aeaeae;
      font-size: 15px
  }

  .text span {
      font-size: 13px;
      color: #545454;
      font-weight: 500
  }

  .icons i {
      font-size: 19px
  }

  hr .new1 {
      border: 1px solid
  }

  .join {
      font-size: 14px;
      #color: #a0a0a0;
      font-weight: bold
  }

  .date {
      background-color: #ccc
  }
</style>
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class="container image d-flex flex-column justify-content-center align-items-center">
            <img src="{{ object.image.url }}" height="100" width="100" />
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>Change image:</div>
                <div class="py-3">{{ form.image }}</div>
                <div>Change email:</div>
                <div class="py-3">{{ form.email }}</div>
                <div>Change bio:</div>
                <div class="py-3">{{ form.bio }}</div>
                <div align="center">
                    <input type="submit" class="btn btn-primary" value="Change Profile" />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

django_web_project/templates/registration.html
{% extends 'base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block content %}
<style>
  .error{
    color: red
  }
</style>
<section class="vh-100 bg-secondary" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Register</p>

                {% if messages %}
                  {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}" {% endif %} >
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}

                <form class="mx-1 mx-md-4" method="POST">

                  {% csrf_token %}

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{ form.username }}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{form.email}}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{form.password1}}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{form.password2}}
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    {{ form.terms_of_service }}
                    <label class="form-check-label ms-2" for="terms_of_service">
                      I agree all statements in <a href="{% url 'accounts_app:terms_of_service' %}">Terms of service</a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <input type="submit" class="btn btn-primary btn-lg" value="Register" />
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

django_web_project/templates/terms_of_service.html
{% extends 'base.html' %}

{% block title %}Terms of service{% endblock %}

{% block content %}
<section class="vh-100 bg-secondary" style="background-color: #eee;">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-lg-12 col-xl-11 my-5">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Terms Of Service</p>
                <div class="container">
                    <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                    </p>

                    <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                        Free terms. Free terms. Free terms. Free terms. Free terms.
                    </p>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}